name: auth-service-dev

env:
  GRADLE_MODULE: services:auth-service
  MODULE_PATH: services/auth-service
  ARTIFACT_NAME: auth-service

on:
  push:
    branches:
      - dev
    paths:
      - services/auth-service/**

jobs:
  docker_build_and_push:
    name: Build and push Docker image to GitHub container registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to OpenShift Container Registry
        uses: docker/login-action@v1
        with:
          registry: registry.redhat.io
          username: ${{ secrets.RHSA_USERNAME }}
          password: ${{ secrets.RHSA_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.CR_OWNER }}
          password: ${{ secrets.CR_PAT }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./${{ env.MODULE_PATH }}/Dockerfile
          push: true
          tags: |
            ghcr.io/city-of-helsinki/haitaton/${{ env.ARTIFACT_NAME }}:latest
            ghcr.io/city-of-helsinki/haitaton/${{ env.ARTIFACT_NAME }}:dev
  temp_test_deploy:
    name: Trigger deployment to temporary test environment at haitaton.kaupunkiymparisto.fi
    needs: docker_build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.DEPLOY_REPO_ACCESS_TOKEN }}
          repository: City-of-Helsinki/haitaton-deploy
          event-type: haitaton-backend
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
