name: CI

on: [ push ]

jobs:
  build:
    name: Gradle Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build with Gradle
        run: sh gradlew build
      - name: Upload application jar file for Docker build job
        if: ${{ github.ref == 'refs/heads/dev' }}
        uses: actions/upload-artifact@v2
        with:
          name: haitaton-hanke-service-jar
          path: build/libs/haitaton-hanke-service-*.jar
          retention-days: 1
  push_to_github_packages:
    name: Build and push Docker image to GitHub Packages
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/dev' }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Download application jar file
        uses: actions/download-artifact@v2
        with:
          name: haitaton-hanke-service-jar
      - name: List files after checkout
        shell: bash
        run: |
          ls -ltra
      - name: Build and push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: city-of-helsinki/haitaton-hanke-service/haitaton-hanke-service-image
          tag_with_ref: true
